# [actions/create-release](https://github.com/actions/create-release)が2022/05/28現在GitHubの開発チームによってメンテナンスされてないので
# 代替案として提案されていたものを使用する

name: create-release-tag
on:
  push:
    branches:
      - main

# TODO: リリースタグ名を YYYY/MM.v形式に変更
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Set current date
      #   env:
      #     TZ: 'Asia/Tokyo'
      #   id: current-date
      #   run:  echo "::set-output name=CURRENT_DATE::$(date +'%Y-%m-%d %H:%M')"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: リリースしたよ
